### ISSUE TITLE
普通開戶后，會員管理 無此會員 信息 

### ISSUE THREAD

**Issue by dajohnny** [solo831927/repo#1]
賬號johnny111 
普通開戶后，/web/agent/memeber 。會員管理/web/agent/member/list 返回的集合無新開戶的信息！

問題1： 期待返回 新開戶的數據；
問題2：返回集合中有自己的數據（這個建議去掉，所謂會員管理顧名思義是 “管理會員”，不應存在本身）

![image](https://user-images.githubusercontent.com/17939743/27268208-b83d6360-54e0-11e7-9cfa-759dd3ff7d83.png)

**Comment by solo831927** [comment]
好的，我下午查一下，这个问题以前fix过了，不知道怎么又出来了
